export const OPTIONS = {
  NO_FILTER: 0,
  ACCEPTED: 1,
  NOT_ACCEPTED: 2,
  TO_CHECK: 3,
};

export const FILTER_LABEL = {
  [OPTIONS.NO_FILTER]: "NF",
  [OPTIONS.ACCEPTED]: "ACP",
  [OPTIONS.NOT_ACCEPTED]: "REC",
  [OPTIONS.TO_CHECK]: "PEN",
};

export const OPTIONS_ARRAY = {
  NO_FILTER: "NF",
  ACCEPTED: "ACP",
  NOT_ACCEPTED: "REC",
  TO_CHECK: "PEN",
};
