export const VIEWS = {
  login: "/login",
  securityHome: "/securityHome",
  dashboard: "/dashboard",
  test: "/test",
  pageNotFound: "*",
  createQR: "/generate-ticket",
  scanQR: "/scan-qr",
  request: "/request",
  myAccount: "/myaccount",
  loader: "/loader",
  modal: "/modal",
  houseList: "/listhouse",
  userList: "/users-list",
  requestList: "/requests-list",
};
